version: '3.5'

services:

  d3-eth-node0:
    build:
      context: ./ethereum
      dockerfile: ganache.dockerfile
    container_name: d3-eth-node0
    ports:
      - 8545:8545
    volumes:
      - ./ethereum:/eth
    environment:
      - NODE=0
    networks:
      - d3-network

  d3-eth-registration:
    image: nexus.iroha.tech:19002/d3-deploy/eth-registration:develop
    container_name: d3-eth-registration
    ports:
      - 8083:8083
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
      - ../deploy/ethereum/keys:/opt/notary/deploy/ethereum/keys
    networks:
      - d3-network

  d3-eth-deploy-relay:
    image: nexus.iroha.tech:19002/d3-deploy/eth-relay:develop
    container_name: d3-eth-deploy-relay
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051, d3-eth-node0:8545
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
      - ../deploy/ethereum/keys:/opt/notary/deploy/ethereum/keys
    networks:
      - d3-network

  d3-eth-deposit:
    image: nexus.iroha.tech:19002/d3-deploy/eth-deposit:develop
    container_name: d3-eth-deposit
    ports:
      - 20000:20000
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051, d3-eth-node0:8545
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
      - ../deploy/ethereum/keys:/opt/notary/deploy/ethereum/keys
    networks:
      - d3-network

  d3-eth-withdrawal:
    image: nexus.iroha.tech:19002/d3-deploy/eth-withdrawal:develop
    container_name: d3-eth-withdrawal
    ports:
      - 8084:8084
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051, d3-eth-node0:8545
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
      - ../deploy/ethereum/keys:/opt/notary/deploy/ethereum/keys
    networks:
      - d3-network

networks:
  d3-network:
