version: '3.5'

networks:
  d3-network:
    name: d3-${SUBNET}
    attachable: true

services:
  d3-iroha:
    container_name: d3-iroha-${SUBNET}
    expose:
    - 50051
    networks:
    - d3-network

  d3-iroha-postgres:
    container_name: d3-iroha-postgres-${SUBNET}
    networks:
    - d3-network

  # ethereum
  d3-eth-node0:
    build:
      context: ./ethereum
      dockerfile: ganache.dockerfile
    container_name: d3-eth-node0-${SUBNET}
    expose:
    - 8545
    volumes:
      - ./ethereum:/eth
    environment:
      - NODE=0
    networks:
    - d3-network

  d3-rmq:
    container_name: d3-rmq-${SUBNET}
    expose:
    - 15672
    - 5672
    networks:
    - d3-network

  d3-chain-adapter:
    container_name: d3-chain-adapter-${SUBNET}
    networks:
    - d3-network

  d3-brvs-mongodb:
    container_name: d3-brvs-mongodb-${SUBNET}
    networks:
    - d3-network

  d3-brvs:
    container_name: d3-brvs-${SUBNET}
    networks:
    - d3-network
