version: '3.5'

services:

  d3-eth-node0:
    build:
      context: ./ethereum
      dockerfile: ganache.dockerfile
    container_name: d3-eth-node0
    ports:
      - 8545:8545
    volumes:
      - ./ethereum:/eth
    environment:
      - NODE=0
    networks:
      - d3-network

  d3-iroha:
    ports:
      - 50051:50051
    networks:
      - d3-network

  d3-rmq:
    ports:
      - 8181:15672
      - 5672:5672
    networks:
      - d3-network

  d3-chain-adapter:
    environment:
      - CHAIN_ADAPTER_DROPLASTREADBLOCK=true

  d3-brvs:
    environment:
      WHITELIST_VALIDATION: 1
